In [1]:
import os
import pandas as pd
import numpy as np
from skimage.io import imread, imshow
from skimage import filters
from skimage import feature
from skimage.filters import prewitt_h,prewitt_v
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import pickle
import re

In [2]:
import os

path = r"C:\Users\shami\images"
filelist = []

for root, dirs, files in os.walk(path):
    for file in files:
        filelist.append(os.path.join(root,file))

In [3]:
from skimage.transform import resize
from csv import writer 
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
from sklearn.model_selection import train_test_split

In [30]:
def append_list_as_row(file_name, list_of_elem):
    with open(file_name, 'a+', newline='') as write_obj:
        csv_writer = writer(write_obj)
        csv_writer.writerow(list_of_elem)

# len(imgs.index.values)
for i in range(len(filelist)):       
    name = filelist[i][22:]
    x1 = imread(filelist[i],as_gray=True)
    x1 = resize(x1, (200,200))
    x1 = feature.canny(x1)
    x1= x1.astype('int32')
    x1 = list(np.concatenate(x1).flat)
    x1.append(name)
    append_list_as_row("hog.csv",x1)

C:\Users\shami\anaconda3\lib\site-packages\PIL\TiffImagePlugin.py:822: UserWarning: Corrupt EXIF data.  Expecting to read 2 bytes but only got 0.
  warnings.warn(str(msg))

In [33]:
cols = np.arange(0,40000)
cols = np.append(cols,'Names')
df = pd.read_csv("numeric_data.csv", names = cols)

In [35]:
df

,0,1,2,3,4,5,6,7,8,9,...,39991,39992,39993,39994,39995,39996,39997,39998,39999,Names
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_1.jpg
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_10.png
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_100.jpg
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_1000.png
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_1001.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_995.jpeg
6988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_996.jpg
6989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_997.jpg
6990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_998.jpg
6991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,image_999.png

In [6]:
import pickle
Pkl_Filename = "df.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(df, file)